[theme]
base = "light"
primaryColor = "#1B4B66"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F8"
textColor = "#1A1A1A"
font = "sans serif"

[client]
showErrorDetails = true

[browser]
gatherUsageStats = false
